name: diary_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.4
  retrofit: ^4.4.2
  get_it: ^8.0.3
  dio: ^5.7.0
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  file_picker: ^9.0.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.7
  json_serializable: ^6.9.3
  build_runner: ^2.4.14
  freezed: ^2.5.8
  
flutter:
  uses-material-design: true

  assets: 
    - .env.dev 
    - .env.prod