name: diary_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  image_picker: ^1.0.7
  path_provider: ^2.1.1
  path: ^1.8.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  file_picker: ^6.1.1
  dartz: ^0.10.1
  retrofit: ^4.4.2
  dio: ^5.7.0
  flutter_svg: ^2.0.17
  provider: ^6.1.4
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.4
  permission_handler: ^11.4.0
  device_info_plus: ^11.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets: 
    - .env.dev 
    - .env.prod
    - assets/images/logo.png

